# Generated by Django 4.1.7 on 2023-02-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirements',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
