# Generated by Django 4.1.7 on 2023-02-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_reciperequirements_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='menu_item',
            new_name='purchased_item',
        ),
    ]
