# Generated by Django 4.1.7 on 2023-02-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_menu_item_purchase_purchased_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_item',
            new_name='menu_item',
        ),
    ]
